[tool.poetry]
name = "tanks"
version = "0.1.0"
description = ""
authors = ["Hunter Bowie <axolotl@students.cs.ubc.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.6.1"
pygame-util = "^1.0.5"
pytest = "^8.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
